import { Inter } from 'next/font/google'
import './globals.css'
import { Context } from './context/context'
import { CSSReset, ChakraProvider } from '@chakra-ui/react'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraProvider>
          <CSSReset />
          <Context>
            {children}
          </Context>
        </ChakraProvider>
      </body>
    </html>
  )
}
